pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.aliyun.com/repository/public' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
}

rootProject.name = mod_id

// Minecraft 1.20.1 Forge-only build
include 'libs:core'
include 'libs:lz4-relocated'
include 'libs:platform-api'
include 'libs:common'
include 'libs:mc-1.20'
include 'mc-1.20.1:forge'